[workspace]
authors = ["lynx2001 <kangaroo125@naver.com>"]
channels = ["conda-forge", "robostack-staging"]
name = "Auto_RC"
platforms = ["osx-arm64", "osx-64", "linux-64"]
version = "0.1.0"

[tasks]
build = "colcon build --symlink-install"

sim = "zsh -c 'source install/setup.zsh && ros2 launch auto_rc sim.launch.py'"
slam = "zsh -c 'source install/setup.zsh && ros2 launch slam_toolbox online_async_launch.py'"
nav = "zsh -c 'source install/setup.zsh && ros2 launch nav2_bringup navigation_launch.py'"

[dependencies]
ros-humble-desktop = "*"
ros-humble-ros-gz = "*"
ros-humble-navigation2 = "*"
ros-humble-nav2-bringup = "*"
ros-humble-slam-toolbox = "*"
ros-humble-robot-localization = "*"
ros-humble-ackermann-msgs = "*"
ros-humble-image-transport = "*"
ros-humble-cv-bridge = "*"
ros-humble-rplidar-ros = "*"
ros-humble-rviz2 = "*"
ros-humble-rqt = "*"
compilers = "*"
cmake = "*"
ninja = "*"
pkg-config = "*"
ros-humble-joint-state-publisher-gui = ">=2.4.0,<3"
colcon-ros = ">=0.5.0,<0.6"
colcon-common-extensions = ">=0.3.0,<0.4"
ros-humble-gazebo-ros-pkgs = "*"


[target.linux-64.dependencies]
ros-humble-v4l2-camera = "*"
